version: '3'
services:

  database:
    image: mysql:5.7
    container_name: mysql
    environment:
        MYSQL_DATABASE: db
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    volumes: 
      - ./mysql-db-local:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  client:
    build:
      context: ./vuejs-app-gke/.
      args:
        - API_PATH=http://localhost:8080
    container_name: vuejs
    environment:
      NODE_ENV: development
    ports:
      - "80:80"
    networks:
      - frontend

  api:
    build: ./springboot-app-gke/.
    container_name: springboot
    depends_on: 
      - "database"
    entrypoint: sh -c "./wait-for database:3306 -t 60 -- java -Dspring.profiles.active=docker -jar app.jar"
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge