apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: easy-mvc
    tier: backend
  spec:
    type: LoadBalancer
    ports:
      port: 8080
    selector:
      app: easy-mvc
      tier: backend