spring:
  profiles:
    active: gke
---
spring:
  profiles: docker
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database:3306/db
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create

---
spring:
  profiles: gke
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${CLOUDSQL_MYSQL_HOST}/easy_mvc_db
    username: ${CLOUDSQL_MYSQL_USER}
    password: ${CLOUDSQL_MYSQL_PASSWORD} 
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create


